openapi: 3.0.0
info:
  title: ianriizky-whatsapp-api
  version: v1
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: home
  - name: connections
paths:
  /:
    get:
      tags:
        - home
      summary: index
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /app-version:
    get:
      tags:
        - home
      summary: app-version
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /connections:
    post:
      tags:
        - connections
      summary: store
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                data:
                  type: connections
                  attributes:
                    phone_number: '6285161456264'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /connections/{phone_number}:
    get:
      tags:
        - connections
      summary: show
      parameters:
        - name: phone_number
          in: path
          schema:
            type: integer
          required: true
          example: '6285161456264'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
